services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "smbs"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d smbs"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - .:/docker-entrypoint-initdb.d

  smbs:
    build: src/
    command: python ./import.py
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
        restart: true
